// Code generated by ent, DO NOT EDIT.

package logevent

const (
	// Label holds the string label denoting the logevent type in the database.
	Label = "log_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// Table holds the table name of the logevent in the database.
	Table = "log_events"
)

// Columns holds all SQL columns for logevent fields.
var Columns = []string{
	FieldID,
	FieldTimestamp,
	FieldLevel,
	FieldMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
