// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LogEventsColumns holds the columns for the "log_events" table.
	LogEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "level", Type: field.TypeInt},
		{Name: "message", Type: field.TypeString},
	}
	// LogEventsTable holds the schema information for the "log_events" table.
	LogEventsTable = &schema.Table{
		Name:       "log_events",
		Columns:    LogEventsColumns,
		PrimaryKey: []*schema.Column{LogEventsColumns[0]},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "version", Type: field.TypeInt},
		{Name: "source_address", Type: field.TypeString},
		{Name: "source_port", Type: field.TypeInt},
		{Name: "destination_address", Type: field.TypeString},
		{Name: "destination_port", Type: field.TypeInt},
		{Name: "size", Type: field.TypeUint32},
		{Name: "source_actor", Type: field.TypeUint32},
		{Name: "target_actor", Type: field.TypeUint32},
		{Name: "segment_type", Type: field.TypeInt},
		{Name: "opcode", Type: field.TypeInt, Nullable: true},
		{Name: "server", Type: field.TypeInt, Nullable: true},
		{Name: "timestamp_raw", Type: field.TypeUint32, Nullable: true},
		{Name: "data", Type: field.TypeBytes, Nullable: true},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LogEventsTable,
		MessagesTable,
	}
)

func init() {
}
