// Code generated by ent, DO NOT EDIT.

package message

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/velcro-xiv/velcro/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestamp), v))
	})
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersion), v))
	})
}

// SourceAddress applies equality check predicate on the "source_address" field. It's identical to SourceAddressEQ.
func SourceAddress(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourceAddress), v))
	})
}

// SourcePort applies equality check predicate on the "source_port" field. It's identical to SourcePortEQ.
func SourcePort(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourcePort), v))
	})
}

// DestinationAddress applies equality check predicate on the "destination_address" field. It's identical to DestinationAddressEQ.
func DestinationAddress(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDestinationAddress), v))
	})
}

// DestinationPort applies equality check predicate on the "destination_port" field. It's identical to DestinationPortEQ.
func DestinationPort(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDestinationPort), v))
	})
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSize), v))
	})
}

// SourceActor applies equality check predicate on the "source_actor" field. It's identical to SourceActorEQ.
func SourceActor(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourceActor), v))
	})
}

// TargetActor applies equality check predicate on the "target_actor" field. It's identical to TargetActorEQ.
func TargetActor(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTargetActor), v))
	})
}

// SegmentType applies equality check predicate on the "segment_type" field. It's identical to SegmentTypeEQ.
func SegmentType(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSegmentType), v))
	})
}

// Opcode applies equality check predicate on the "opcode" field. It's identical to OpcodeEQ.
func Opcode(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOpcode), v))
	})
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServer), v))
	})
}

// TimestampRaw applies equality check predicate on the "timestamp_raw" field. It's identical to TimestampRawEQ.
func TimestampRaw(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestampRaw), v))
	})
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldData), v))
	})
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestamp), v))
	})
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTimestamp), v))
	})
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTimestamp), v...))
	})
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTimestamp), v...))
	})
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTimestamp), v))
	})
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTimestamp), v))
	})
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTimestamp), v))
	})
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTimestamp), v))
	})
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVersion), v))
	})
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVersion), v))
	})
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldVersion), v...))
	})
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldVersion), v...))
	})
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVersion), v))
	})
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVersion), v))
	})
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVersion), v))
	})
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVersion), v))
	})
}

// SourceAddressEQ applies the EQ predicate on the "source_address" field.
func SourceAddressEQ(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressNEQ applies the NEQ predicate on the "source_address" field.
func SourceAddressNEQ(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressIn applies the In predicate on the "source_address" field.
func SourceAddressIn(vs ...string) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSourceAddress), v...))
	})
}

// SourceAddressNotIn applies the NotIn predicate on the "source_address" field.
func SourceAddressNotIn(vs ...string) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSourceAddress), v...))
	})
}

// SourceAddressGT applies the GT predicate on the "source_address" field.
func SourceAddressGT(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressGTE applies the GTE predicate on the "source_address" field.
func SourceAddressGTE(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressLT applies the LT predicate on the "source_address" field.
func SourceAddressLT(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressLTE applies the LTE predicate on the "source_address" field.
func SourceAddressLTE(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressContains applies the Contains predicate on the "source_address" field.
func SourceAddressContains(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressHasPrefix applies the HasPrefix predicate on the "source_address" field.
func SourceAddressHasPrefix(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressHasSuffix applies the HasSuffix predicate on the "source_address" field.
func SourceAddressHasSuffix(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressEqualFold applies the EqualFold predicate on the "source_address" field.
func SourceAddressEqualFold(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSourceAddress), v))
	})
}

// SourceAddressContainsFold applies the ContainsFold predicate on the "source_address" field.
func SourceAddressContainsFold(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSourceAddress), v))
	})
}

// SourcePortEQ applies the EQ predicate on the "source_port" field.
func SourcePortEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourcePort), v))
	})
}

// SourcePortNEQ applies the NEQ predicate on the "source_port" field.
func SourcePortNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSourcePort), v))
	})
}

// SourcePortIn applies the In predicate on the "source_port" field.
func SourcePortIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSourcePort), v...))
	})
}

// SourcePortNotIn applies the NotIn predicate on the "source_port" field.
func SourcePortNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSourcePort), v...))
	})
}

// SourcePortGT applies the GT predicate on the "source_port" field.
func SourcePortGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSourcePort), v))
	})
}

// SourcePortGTE applies the GTE predicate on the "source_port" field.
func SourcePortGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSourcePort), v))
	})
}

// SourcePortLT applies the LT predicate on the "source_port" field.
func SourcePortLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSourcePort), v))
	})
}

// SourcePortLTE applies the LTE predicate on the "source_port" field.
func SourcePortLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSourcePort), v))
	})
}

// DestinationAddressEQ applies the EQ predicate on the "destination_address" field.
func DestinationAddressEQ(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressNEQ applies the NEQ predicate on the "destination_address" field.
func DestinationAddressNEQ(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressIn applies the In predicate on the "destination_address" field.
func DestinationAddressIn(vs ...string) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDestinationAddress), v...))
	})
}

// DestinationAddressNotIn applies the NotIn predicate on the "destination_address" field.
func DestinationAddressNotIn(vs ...string) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDestinationAddress), v...))
	})
}

// DestinationAddressGT applies the GT predicate on the "destination_address" field.
func DestinationAddressGT(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressGTE applies the GTE predicate on the "destination_address" field.
func DestinationAddressGTE(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressLT applies the LT predicate on the "destination_address" field.
func DestinationAddressLT(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressLTE applies the LTE predicate on the "destination_address" field.
func DestinationAddressLTE(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressContains applies the Contains predicate on the "destination_address" field.
func DestinationAddressContains(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressHasPrefix applies the HasPrefix predicate on the "destination_address" field.
func DestinationAddressHasPrefix(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressHasSuffix applies the HasSuffix predicate on the "destination_address" field.
func DestinationAddressHasSuffix(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressEqualFold applies the EqualFold predicate on the "destination_address" field.
func DestinationAddressEqualFold(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDestinationAddress), v))
	})
}

// DestinationAddressContainsFold applies the ContainsFold predicate on the "destination_address" field.
func DestinationAddressContainsFold(v string) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDestinationAddress), v))
	})
}

// DestinationPortEQ applies the EQ predicate on the "destination_port" field.
func DestinationPortEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDestinationPort), v))
	})
}

// DestinationPortNEQ applies the NEQ predicate on the "destination_port" field.
func DestinationPortNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDestinationPort), v))
	})
}

// DestinationPortIn applies the In predicate on the "destination_port" field.
func DestinationPortIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDestinationPort), v...))
	})
}

// DestinationPortNotIn applies the NotIn predicate on the "destination_port" field.
func DestinationPortNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDestinationPort), v...))
	})
}

// DestinationPortGT applies the GT predicate on the "destination_port" field.
func DestinationPortGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDestinationPort), v))
	})
}

// DestinationPortGTE applies the GTE predicate on the "destination_port" field.
func DestinationPortGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDestinationPort), v))
	})
}

// DestinationPortLT applies the LT predicate on the "destination_port" field.
func DestinationPortLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDestinationPort), v))
	})
}

// DestinationPortLTE applies the LTE predicate on the "destination_port" field.
func DestinationPortLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDestinationPort), v))
	})
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSize), v))
	})
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSize), v))
	})
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSize), v...))
	})
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSize), v...))
	})
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSize), v))
	})
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSize), v))
	})
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSize), v))
	})
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSize), v))
	})
}

// SourceActorEQ applies the EQ predicate on the "source_actor" field.
func SourceActorEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSourceActor), v))
	})
}

// SourceActorNEQ applies the NEQ predicate on the "source_actor" field.
func SourceActorNEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSourceActor), v))
	})
}

// SourceActorIn applies the In predicate on the "source_actor" field.
func SourceActorIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSourceActor), v...))
	})
}

// SourceActorNotIn applies the NotIn predicate on the "source_actor" field.
func SourceActorNotIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSourceActor), v...))
	})
}

// SourceActorGT applies the GT predicate on the "source_actor" field.
func SourceActorGT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSourceActor), v))
	})
}

// SourceActorGTE applies the GTE predicate on the "source_actor" field.
func SourceActorGTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSourceActor), v))
	})
}

// SourceActorLT applies the LT predicate on the "source_actor" field.
func SourceActorLT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSourceActor), v))
	})
}

// SourceActorLTE applies the LTE predicate on the "source_actor" field.
func SourceActorLTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSourceActor), v))
	})
}

// TargetActorEQ applies the EQ predicate on the "target_actor" field.
func TargetActorEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTargetActor), v))
	})
}

// TargetActorNEQ applies the NEQ predicate on the "target_actor" field.
func TargetActorNEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTargetActor), v))
	})
}

// TargetActorIn applies the In predicate on the "target_actor" field.
func TargetActorIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTargetActor), v...))
	})
}

// TargetActorNotIn applies the NotIn predicate on the "target_actor" field.
func TargetActorNotIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTargetActor), v...))
	})
}

// TargetActorGT applies the GT predicate on the "target_actor" field.
func TargetActorGT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTargetActor), v))
	})
}

// TargetActorGTE applies the GTE predicate on the "target_actor" field.
func TargetActorGTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTargetActor), v))
	})
}

// TargetActorLT applies the LT predicate on the "target_actor" field.
func TargetActorLT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTargetActor), v))
	})
}

// TargetActorLTE applies the LTE predicate on the "target_actor" field.
func TargetActorLTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTargetActor), v))
	})
}

// SegmentTypeEQ applies the EQ predicate on the "segment_type" field.
func SegmentTypeEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSegmentType), v))
	})
}

// SegmentTypeNEQ applies the NEQ predicate on the "segment_type" field.
func SegmentTypeNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSegmentType), v))
	})
}

// SegmentTypeIn applies the In predicate on the "segment_type" field.
func SegmentTypeIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSegmentType), v...))
	})
}

// SegmentTypeNotIn applies the NotIn predicate on the "segment_type" field.
func SegmentTypeNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSegmentType), v...))
	})
}

// SegmentTypeGT applies the GT predicate on the "segment_type" field.
func SegmentTypeGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSegmentType), v))
	})
}

// SegmentTypeGTE applies the GTE predicate on the "segment_type" field.
func SegmentTypeGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSegmentType), v))
	})
}

// SegmentTypeLT applies the LT predicate on the "segment_type" field.
func SegmentTypeLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSegmentType), v))
	})
}

// SegmentTypeLTE applies the LTE predicate on the "segment_type" field.
func SegmentTypeLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSegmentType), v))
	})
}

// OpcodeEQ applies the EQ predicate on the "opcode" field.
func OpcodeEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldOpcode), v))
	})
}

// OpcodeNEQ applies the NEQ predicate on the "opcode" field.
func OpcodeNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldOpcode), v))
	})
}

// OpcodeIn applies the In predicate on the "opcode" field.
func OpcodeIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldOpcode), v...))
	})
}

// OpcodeNotIn applies the NotIn predicate on the "opcode" field.
func OpcodeNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldOpcode), v...))
	})
}

// OpcodeGT applies the GT predicate on the "opcode" field.
func OpcodeGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldOpcode), v))
	})
}

// OpcodeGTE applies the GTE predicate on the "opcode" field.
func OpcodeGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldOpcode), v))
	})
}

// OpcodeLT applies the LT predicate on the "opcode" field.
func OpcodeLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldOpcode), v))
	})
}

// OpcodeLTE applies the LTE predicate on the "opcode" field.
func OpcodeLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldOpcode), v))
	})
}

// OpcodeIsNil applies the IsNil predicate on the "opcode" field.
func OpcodeIsNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldOpcode)))
	})
}

// OpcodeNotNil applies the NotNil predicate on the "opcode" field.
func OpcodeNotNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldOpcode)))
	})
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldServer), v))
	})
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldServer), v))
	})
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldServer), v...))
	})
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...int) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldServer), v...))
	})
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldServer), v))
	})
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldServer), v))
	})
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldServer), v))
	})
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v int) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldServer), v))
	})
}

// ServerIsNil applies the IsNil predicate on the "server" field.
func ServerIsNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldServer)))
	})
}

// ServerNotNil applies the NotNil predicate on the "server" field.
func ServerNotNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldServer)))
	})
}

// TimestampRawEQ applies the EQ predicate on the "timestamp_raw" field.
func TimestampRawEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawNEQ applies the NEQ predicate on the "timestamp_raw" field.
func TimestampRawNEQ(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawIn applies the In predicate on the "timestamp_raw" field.
func TimestampRawIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldTimestampRaw), v...))
	})
}

// TimestampRawNotIn applies the NotIn predicate on the "timestamp_raw" field.
func TimestampRawNotIn(vs ...uint32) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldTimestampRaw), v...))
	})
}

// TimestampRawGT applies the GT predicate on the "timestamp_raw" field.
func TimestampRawGT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawGTE applies the GTE predicate on the "timestamp_raw" field.
func TimestampRawGTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawLT applies the LT predicate on the "timestamp_raw" field.
func TimestampRawLT(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawLTE applies the LTE predicate on the "timestamp_raw" field.
func TimestampRawLTE(v uint32) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTimestampRaw), v))
	})
}

// TimestampRawIsNil applies the IsNil predicate on the "timestamp_raw" field.
func TimestampRawIsNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldTimestampRaw)))
	})
}

// TimestampRawNotNil applies the NotNil predicate on the "timestamp_raw" field.
func TimestampRawNotNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldTimestampRaw)))
	})
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldData), v))
	})
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldData), v))
	})
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...[]byte) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldData), v...))
	})
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...[]byte) predicate.Message {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldData), v...))
	})
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldData), v))
	})
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldData), v))
	})
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldData), v))
	})
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v []byte) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldData), v))
	})
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldData)))
	})
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldData)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		p(s.Not())
	})
}
