// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LogEvent is the predicate function for logevent builders.
type LogEvent func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
